/**
 * @file    bsp_uart.h
 * @brief   USART1 shared transport interface
 * @details Centralizes the transmit mode selection used by both BSP UART
 *          helpers and the VOFA transport layer.
 *
 * Hardware parameters such as baud rate and clock source are generated by
 * CubeMX in usart.c. This module only selects how bytes are sent:
 * blocking transmit or DMA transmit.
 */

#ifndef __BSP_UART_H
#define __BSP_UART_H

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

/*=============================================================================
 *  Shared transmit mode configuration
 *=============================================================================*/

#define BSP_UART_TX_MODE_BLOCKING   0U
#define BSP_UART_TX_MODE_DMA        1U

/**
 * @brief Shared USART1 transmit mode for BSP and VOFA.
 * @note  Switch this macro to change both layers together.
 */
#define BSP_UART_TX_MODE            BSP_UART_TX_MODE_DMA

/**
 * @brief Shared transmit wait timeout in milliseconds.
 * @note  In DMA mode this is the maximum wait time while the previous frame is
 *        still in progress. In fallback blocking mode it is used as the HAL
 *        transmit timeout.
 */
#define BSP_UART_TX_TIMEOUT_MS      10U

/**
 * @brief Compatibility macro for old code paths.
 */
#define BSP_UART_USE_DMA            (BSP_UART_TX_MODE == BSP_UART_TX_MODE_DMA)

/**
 * @brief Compatibility macro for old code paths.
 */
#define BSP_UART_DMA_TIMEOUT_MS     BSP_UART_TX_TIMEOUT_MS

/*=============================================================================
 *  Public API
 *=============================================================================*/

void BSP_UART_Init(void);

/**
 * @brief Shared low-level transmit entry used by BSP and VOFA.
 * @param data Payload pointer.
 * @param len Payload length.
 * @param timeout_ms Wait timeout in milliseconds. Pass 0 to use the shared
 *        default timeout configured by BSP_UART_TX_TIMEOUT_MS.
 * @return HAL status code.
 */
HAL_StatusTypeDef BSP_UART_Transmit(const uint8_t *data, uint16_t len, uint32_t timeout_ms);

void BSP_UART_SendByte(uint8_t data);
void BSP_UART_SendString(const char *str);
void BSP_UART_SendData(uint8_t *data, uint16_t len);
uint8_t BSP_UART_ReceiveByte(void);
void BSP_UART_Printf(const char *fmt, ...);

#if BSP_UART_USE_DMA
/**
 * @brief Notify the shared UART transport that one DMA transmit has completed.
 * @note  Call this from HAL_UART_TxCpltCallback().
 */
void BSP_UART_DMA_TxCpltCallback(UART_HandleTypeDef *huart);
#endif

/**
 * @brief Query whether the shared USART1 transport is busy.
 * @return 1 when DMA transfer is in progress, otherwise 0.
 */
uint8_t BSP_UART_IsBusy(void);

#ifdef __cplusplus
}
#endif

#endif /* __BSP_UART_H */
